apiVersion: v1
kind: Pod
metadata:
  name: mysqldbinit
  labels:
    app: mysqldbinit
spec:
  containers:
    - name: mysqldbinit
      image: public.ecr.aws/e2e1z6b2/django_db_init
      env:
        - name: SQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql.secret
              key: root_password
        - name: SQL_HOST
          valueFrom:
            configMapKeyRef:
              name: django.config
              key: SQL_HOST
