# Generated by Django 5.1.1 on 2024-09-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumb',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
